#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Feb 11 23:50:04 KST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.7.1.zip
